name = "getada"
description = "The unofficial installer for Alire."
version = "1.0.0"
licenses = "GPL-3.0-only"

authors = ["A.J. Ianozi"]
maintainers = ["A.J. Ianozi <aj@ianozi.com>"]
maintainers-logins = ["AJ-Ianozi"]

executables = ["getada"]

[[depends-on]]
json = "^5.0.3"
zipada = "^58.0.0"
