name: Build GetAda

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ###  Test on windows
  build-linux_x86_64:

    runs-on: ubuntu-20.04

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up alire
      uses: alire-project/setup-alire@v1

    - name: Build alire
      run: >
        alr -n update &&
        alr -n build --release
      
    - name: Compress getada
      run: zip -r getada-linux_x86_64.zip bin
    
    - name: Uploadgetada
      uses: actions/upload-artifact@v2
      with:
         name: getada-linux_x86_64.zip
         path: getada-linux_x86_64.zip

  ###  x86-64 MacOS
  build-macos_x86_64:
    runs-on: macos-12
    
    steps: 
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up alire
        uses: alire-project/setup-alire@v1

      - name: Build getada
        run: >
         alr -n update &&
         alr -n build --release
      
      - name: Compress getada
        run: zip -r getada-macos_x86_64.zip bin
    
      - name: Uploadgetada
        uses: actions/upload-artifact@v2
        with:
         name: getada-macos_x86_64.zip
         path: getada-macos_x86_64.zip
  

         build-windows:
          runs-on: windows-latest
          
          steps: 
          
            - name: Checkout
              uses: actions/checkout@v3
      
            - name: Set up alire
              uses: alire-project/setup-alire@v1
      
            - name: Build alire
              run: >
               alr -n update &&
               alr -n build --release
            ### Don't build a release
      #      - name: Compress getada
      #        run: 7z a -tzip getada-win.zip bin
      #    
      #      - name: Uploadgetada
      #        uses: actions/upload-artifact@v2
      #        with:
      #         name: getada-win.zip
      #         path: getada-win.zip

         ###  Do this after alr2.0 supports our needs
#  build-macos_aarch64:
#    runs-on: macos-14
#    #  May not need this once alr2 comes out?
#    steps: 
#      - name: Install gcc
#        id: install-pkg
#        uses: joncrain/macos-pkg-install@v1.0
#        with:
#          pkg_url: https://github.com/simonjwright/distributing-gcc/releases/download/gcc-13.2.0-aarch64-arm-eabi/gcc-13.2.0-aarch64-arm-eabi.pkg
#
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Set up alire
#        uses: alire-project/setup-alire@v1
#
#      - name: Build alire
#        run: >
#         alr -n update &&
#         alr -n build --release
#      
#      - name: Compress getada
#        run: zip -r getada-development-macos_aarch64.zip bin
#    
#      - name: Uploadgetada
#        uses: actions/upload-artifact@v2
#        with:
#         name: getada-development-macos_aarch64.zip
#         path: getada-development-macos_aarch64.zip

###  Don't have toolchains for gnat on aarch64
#  build-linux_aarch64:
#    runs-on: macos-14
#    
#    steps: 
#    
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Install Homebrew
#        run: |
#         brew tap messense/macos-cross-toolchains
#         brew install aarch64-unknown-linux-gnu
#         aarch64-linux-gnu-gcc -v
