name: Build GetAda

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ###  Build on linux
  build-linux_x86_64:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up alire
      uses: alire-project/setup-alire@v3

    - name: Build alire
      run: >
        alr -n update &&
        alr -n build --release
  
    - name: Compress getada
      run: zip -r getada-linux_x86_64.zip bin

    - name: Uploadgetada
      uses: actions/upload-artifact@v4
      with:
         name: getada-linux_x86_64.zip
         path: getada-linux_x86_64.zip

  ###  x86-64 MacOS
  build-macos_x86_64:
    runs-on: macos-12

    steps: 
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up alire
        uses: alire-project/setup-alire@v3

      - name: Build getada
        run: >
         alr -n update &&
         alr -n build --release

      - name: Compress getada
        run: zip -r getada-macos_x86_64.zip bin
    
      - name: Uploadgetada
        uses: actions/upload-artifact@v4
        with:
         name: getada-macos_x86_64.zip
         path: getada-macos_x86_64.zip

  build-macos_aarch64:
    runs-on: macos-14

    steps: 
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up alire
        uses: robinraju/release-downloader@v1
        with:
          repository: 'alire-project/alire'
          fileName: '*-bin-aarch64-macos.zip'
          out-file-path: 'alire'
          latest: true
          extract: true

      - name: Add alire to path
        run: >
          chmod +x alire/bin/alr &&
          echo "$PWD/alire/bin" >> $GITHUB_PATH

      - name: Configure alire
        run: alr toolchain --disable-assistant --select

      - name: Build getada
        run: >
         alr -n update &&
         alr -n build --release

      - name: Compress getada
        run: zip -r getada-macos_aarch64.zip bin
    
      - name: Uploadgetada
        uses: actions/upload-artifact@v4
        with:
         name: getada-macos_aarch64.zip
         path: getada-macos_aarch64.zip

###  Test on windows
###  I removed this because you shouldn't be using windows for getada.
#  build-windows:
#    runs-on: windows-latest
#
#    steps:
#
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Set up alire
#        uses: alire-project/setup-alire@v1
#
#      - name: Build getada
#        run: >
#         alr -n update &&
#         alr -n build --release
#      ### Don't build a release
#      - name: Compress getada
#        run: 7z a -tzip getada-win.zip bin
#    
#      - name: Uploadgetada
#        uses: actions/upload-artifact@v2
#        with:
#         name: getada-win.zip
#         path: getada-win.zip



###  Don't have toolchains for gnat on aarch64
#  build-linux_aarch64:
#    runs-on: macos-14
#    
#    steps: 
#    
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Install Homebrew
#        run: |
#         brew tap messense/macos-cross-toolchains
#         brew install aarch64-unknown-linux-gnu
#         aarch64-linux-gnu-gcc -v
