name: Ada (GNAT)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up alire
      uses: alire-project/setup-alire@v1

    - name: Build alire
      run: >
        alr -n update &&
        alr -n build --release
      
    - name: Compress getada
      run: tar -cf getada-development-linux.tar bin
    
    - name: Uploadgetada
      uses: actions/upload-artifact@v2
      with:
         name: getada-development-linux.tar
         path: getada-development-linux.tar


  build-windows:
    runs-on: windows-latest
    
    steps: 
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up alire
        uses: alire-project/setup-alire@v1

      - name: Build alire
        run: >
         alr -n update &&
         alr -n build --release
      
      - name: Compress getada
        run: 7z a -tzip getada-development-win.zip bin
    
      - name: Uploadgetada
        uses: actions/upload-artifact@v2
        with:
         name: getada-development-win.zip
         path: getada-development-win.zip


  build-macos:
    runs-on: macos-latest
    
    steps: 
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up alire
        uses: alire-project/setup-alire@v1

      - name: Build alire
        run: >
         alr -n update &&
         alr -n build --release
      
      - name: Compress getada
        run: zip -r getada-development-macos.zip bin
    
      - name: Uploadgetada
        uses: actions/upload-artifact@v2
        with:
         name: getada-development-macos.zip
         path: getada-development-macos.zip
  
