name: Generate GetAda.dev

on:
   workflow_dispatch:

# Use this stuff
# https://github.com/cpina/github-action-push-to-another-repository
# https://github.com/marketplace/actions/setup-appimage for
#    https://github.com/yet-another-static-site-generator/yass/releases/tag/v3.0

jobs:
   Generate_Website:
      runs-on: ubuntu-20.04

      steps:

         - name: Checkout
           uses: actions/checkout@v3

         - name: Install YASS
           uses: robinraju/release-downloader@v1
           with:
            repository: 'yet-another-static-site-generator/yass'
            fileName: 'yass-linux_x86_64.zip '
            latest: true
            extract: true
         
         - name: Compile Yass
           run: >
             ls -la
